name: github-pages

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup Haxe 🕹️
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies 🎲
        run: yes | haxelib --quiet install build-js.hxml
      # Could add a actions/cache@v1 to speedup packages?

      - name: Write version 📝
        run: echo "git-$(git rev-parse --short HEAD) ($(date -d @$(git show -s --format=%ct HEAD) -I))" > res/heaps/version.txt

      - name: Build asset package 🎮
        run: bash run buildres_py

      - name: Compile 🛠️
        run: bash run compile

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www